# **Read Dat files, extract SYNC, PRODUCE sync for the rest from npy files**
## MAEVA rats

## **DOCUMENTATION OPEN EPHYS**
https://open-ephys.github.io/gui-docs/User-Manual/Plugins/Neuropixels-PXI.html

In [2]:
import numpy as np
import os

In [44]:
os.chdir("/media/data-116/Dax/1.Data/2021-05-25_12-32-00/Record Node 102/experiment1/recording1/events/Neuropix-PXI-100.1/TTL_2")

In [30]:
TTL2_folder="/media/data-116/Dax/1.Data/2021-05-25_12-32-00/Record Node 102/experiment1/recording1/events/Neuropix-PXI-100.1/TTL_2"

In [10]:
os.listdir()

['channel_states.npy', 'channels.npy', 'full_words.npy', 'timestamps.npy']

## FILES FROM TTL_2

In [23]:
samp_freq_lfp=25 ##!!!!!!! the sampling freq is 25 in TTL_2

### TIMESTAMP_events

In [45]:
timestamps_events=np.load("timestamps.npy")

In [54]:
timestamps_events[:20]

array([1245560, 1245585, 1245660, 1245685, 1245760, 1245785, 1245860,
       1245885, 1245960, 1245985, 1246060, 1246085, 1246160, 1246185,
       1246260, 1246285, 1246360, 1246385, 1246460, 1246485])

In [46]:
len(timestamps_events)/(samp_freq_lfp*3600*2) #= time of video (~12h) 

#it's a point per frame in vid

11.98938888888889

In [47]:
#diff the timestamp
timestamps_diffed=np.diff(timestamps_events)
timestamps_diffed[:10]

array([25, 75, 25, 75, 25, 75, 25, 75, 25, 75])

### FULL_WORDS

In [16]:
full_words=np.load("full_words.npy")

In [17]:
full_words[:20]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
      dtype=uint8)

In [20]:
len(full_words)/samp_freq_lfp #??? shouldn't be longer?

863.236

### CHANNEL_STATES
+ the same as full_words (excpet instead -1 you have 0 in full_words)

In [26]:
channel_states=np.load("channel_states.npy")

In [27]:
channel_states[:20]

array([-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,
        1, -1,  1], dtype=int16)

## TIMESTAMP_LFP (from continuous)

In [48]:
lfp_tmp_folder="/media/data-116/Dax/1.Data/2021-05-25_12-32-00/Record Node 102/experiment1/recording1/continuous/Neuropix-PXI-100.1"

In [49]:
os.chdir(lfp_tmp_folder)

In [50]:
timestamps_lfp=np.load("timestamps.npy")

## Caculate videoframe timepoints

In [57]:
timestamps_video_frames = timestamps_events[channel_states == 1] - timestamps_lfp[0] - 1